language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION=2.3.*
    - php: 7.1
      env: SYMFONY_VERSION=2.7.*
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=3.0.*
    - php: 7.1
      env: SYMFONY_VERSION=3.1.*
    - php: 7.1
      env: SYMFONY_VERSION=3.2.*

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - SYMFONY_ENV=test

before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
